# Generated by Django 5.0.2 on 2024-02-21 07:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='archivesapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='pdf_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('text', models.TextField(blank=True, null=True)),
                ('Pic', models.ImageField(blank=True, null=True, upload_to='img')),
                ('vidio', models.FileField(blank=True, null=True, upload_to='vidio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
