# Generated by Django 5.0.2 on 2024-02-21 08:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivesapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTypeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt'])])),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('text', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='img')),
                ('video', models.FileField(blank=True, null=True, upload_to='vidio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('filetype', models.CharField(choices=[('F', 'File'), ('A', 'Audio'), ('T', 'Text'), ('P', 'Picture'), ('V', 'Video')], default=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt'])]), max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='archivesapp',
        ),
    ]
