# Generated by Django 5.0.2 on 2024-02-21 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivesapp', '0002_archivetypefile_delete_archivesapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivetypefile',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'WAV', 'VMA'])]),
        ),
        migrations.AlterField(
            model_name='archivetypefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'html', 'xml', 'csv'])]),
        ),
        migrations.AlterField(
            model_name='archivetypefile',
            name='filetype',
            field=models.CharField(choices=[('F', 'File'), ('A', 'Audio'), ('T', 'Text'), ('P', 'Picture'), ('V', 'Video')], max_length=200),
        ),
        migrations.AlterField(
            model_name='archivetypefile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vidio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv'])]),
        ),
    ]
