# Generated by Django 5.0.2 on 2024-02-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivesapp', '0003_alter_archivetypefile_audio_and_more'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivetypefile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
