# Generated by Django 5.0.2 on 2024-02-21 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivesapp', '0004_archivetypefile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivetypefile',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='archivetypefile',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='archivetypefile',
            name='text',
        ),
        migrations.RemoveField(
            model_name='archivetypefile',
            name='video',
        ),
        migrations.AlterField(
            model_name='archivetypefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'html', 'xml', 'csv', 'mp3', 'WAV', 'VMA', 'img', 'mp4', 'mkv'])]),
        ),
    ]
