# Generated by Django 5.0.2 on 2024-02-21 10:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivesapp', '0006_archivetypefile_audio_archivetypefile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'html', 'xml', 'csv'])])),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'WAV', 'VMA'])])),
                ('text', models.TextField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='img')),
                ('video', models.FileField(blank=True, null=True, upload_to='vidio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv'])])),
            ],
        ),
        migrations.RemoveField(
            model_name='archivetypefile',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='archivetypefile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='archivetypefile',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='archivetypefile',
            name='text',
        ),
        migrations.RemoveField(
            model_name='archivetypefile',
            name='video',
        ),
        migrations.AlterField(
            model_name='archivetypefile',
            name='filetype',
            field=models.CharField(blank=True, choices=[('F', 'File'), ('A', 'Audio'), ('T', 'Text'), ('P', 'Picture'), ('V', 'Video')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='archivetypefile',
            name='fileupload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archivesapp.archivesmodel'),
        ),
    ]
