# Generated by Django 5.0.2 on 2024-02-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivesapp', '0010_rename_mediatype_archivetypefile_mediatype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivetypefile',
            name='media',
        ),
    ]
